version: '3.8'

services:
  app:
    build: .
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    restart: unless-stopped
    volumes:
      - ./public/uploads:/app/public/uploads
    networks:
      - app-network

  chat:
    build:
      context: ../chat-app
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - ../chat-app/.env
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./ssl:/etc/ssl/cloudflare
    depends_on:
      - app
      - chat
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge